services:
  afba:
    container_name: afba
    build:
      context: .
      dockerfile: prod.Dockerfile
    depends_on:
      - afba-database

    # Set environment variables directly in the docker-compose file
    environment:
      ENV_VARIABLE: ${ENV_VARIABLE}
      NEXT_PUBLIC_ENV_VARIABLE: ${NEXT_PUBLIC_ENV_VARIABLE}

    # Set environment variables based on the .env file
    env_file:
      - .env
    volumes:
      - .:/app
      - ./public:/app/public
    restart: always
    ports:
      - 3000:3000
      - 9229:9229
      - 9230:9230
    networks:
      - afba_network
 
  afba-database:
    container_name: mongodb
    image: mongo
    ports:
      - 27017:27017
    networks:
      - afba_network

# Define a network, which allows containers to communicate
# with each other, by using their container name as a hostname
networks:
  afba_network:
    external: false

