name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest
    environment: production

    env:
      DOCKER_USER: ${{vars.DOCKER_USER}}
      DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      REPO_NAME: ${{vars.REPO_NAME}}

    steps:

    - name: log env variables
      run: echo "${{env.DOCKER_USER}}"

    - uses: actions/checkout@v4
    - name: Docker Login
      run: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    
    - name: Build the Docker Image
      run: docker compose build

    - name: Push Docker Image
      run: docker push $DOCKER_USER/$REPO_NAME:latest
