name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  DOCKER_USER: ${{secrets.DOCKER_USER}}
  DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
  REPO_NAME: ${{secrets.REPO_NAME}}

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v4
    - name: Docker Login
      run: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    
    - name: Build the Docker Image
      run: docker compose build -tag latest

    - name: Push Docker Image
      run: docker push $DOCKER_USER/$REPO_NAME:latest
